README.md, examples/blender/blender.js, examples/blender/blender.ts, examples/low-level-api/listOffers.js, examples/low-level-api/listOffers.ts, package.json, yajsapi/rest/activity.ts, yajsapi/rest/market.ts, yajsapi/rest/payment.ts, yajsapi/runner/ctx.ts, yajsapi/runner/index.ts, yajsapi/storage/gftp.ts, yajsapi/utils/asyncWith.ts, yajsapi/utils/commander.ts, yajsapi/utils/index.ts, yajsapi/utils/log.ts
=> Add logger, argument parser, trim unnecessary logs

examples/package.json, package.json
Resolves #21.
Will require update on handbook.
=> Yajsapi on npm

yajsapi/rest/payment.ts, yajsapi/utils/log.ts
=> Fix no acceptance definition

yajsapi/utils/log.ts
=> Fix double spending information display

yajsapi/rest/activity.ts, yajsapi/runner/events.ts, yajsapi/runner/index.ts, yajsapi/runner/smartq.ts, yajsapi/runner/task.ts, yajsapi/utils/asyncWith.ts, yajsapi/utils/log.ts
=> fix consumer flow with asyncWith wrapper, fix logs

yajsapi/runner/index.ts, yajsapi/runner/smartq.ts
=> Sign new agreements only if there are unassigned tasks

yajsapi/rest/activity.ts, yajsapi/runner/events.ts, yajsapi/runner/index.ts, yajsapi/utils/log.ts
=> Fix long computations failing on providers

examples/low-level-api/listOffers.ts, package.json
=> axios, ya-ts-client version bump, update example

.gitignore, .npmignore, yajsapi/utils/log.ts
=> Fix file transport and total cost amount

examples/blender/blender.js, examples/blender/blender.ts, examples/low-level-api/listOffers.js, examples/low-level-api/listOffers.ts, examples/package.json, package.json, yajsapi/executor/events.ts, yajsapi/executor/index.ts, yajsapi/executor/smartq.ts, yajsapi/package/index.ts, yajsapi/props/base.ts, yajsapi/rest/activity.ts, yajsapi/rest/market.ts, yajsapi/rest/payment.ts, yajsapi/storage/gftp.ts, yajsapi/utils/queue.ts
=> Graceful quit

examples/blender/blender.js, examples/blender/blender.ts, package.json, yajsapi/package/index.ts
* bump version
* update the fallback repo url
* update the subnet
=> update the fallback repo url, update the default subnet

handbook_gen/handbook_gen.py, handbook_gen/pyproject.toml, handbook_gen/templates/summary.mako, package.json
=> + handbook generator

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, tests/goth/conftest.py, tests/goth/empty.py, tests/goth/pyproject.toml, tests/goth/test_run_blender.py, yajsapi/executor/index.ts, yajsapi/rest/configuration.ts, yajsapi/utils/log.ts
=> Integration tests using goth

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, tests/goth/conftest.py, tests/goth/pyproject.toml, tests/goth/test_run_blender.py, yajsapi/executor/index.ts, yajsapi/rest/configuration.ts, yajsapi/utils/log.ts
=> Integration tests -> b0.3

yajsapi/executor/index.ts
Reverts golemfactory/yajsapi#173
=> Revert "Fix map indexing bug"

yajsapi/executor/index.ts
Reverts golemfactory/yajsapi#174
=> Revert "Revert "Fix map indexing bug""

.github/workflows/integration-tests.yml
A port of changes introduced here: https://github.com/golemfactory/goth/pull/475
=> Add Docker cleanup before running integration tests

yajsapi/executor/index.ts, yajsapi/rest/activity.ts, yajsapi/rest/market.ts, yajsapi/utils/log.ts
https://github.com/golemfactory/yajsapi/pull/177/commits/5ca13671f7391724f5a4683a8005d31b053220d2 contains all important changes, please review it (a separate commit modifies code indentation).
=> Port subscription expiration from yapapi

tests/goth/pyproject.toml
Cherry-pick of https://github.com/golemfactory/yajsapi/pull/198
=> Bump goth version to 0.3.*

yajsapi/rest/common.ts, yajsapi/rest/payment.ts
Reverts golemfactory/yajsapi#216
=> Revert "Minimal repeat API calls fix"

.github/workflows/goth-nightly.yml
Updating so that it's consistent with the changes merged to the `yagna` nightly workflow: https://github.com/golemfactory/yagna/pull/1433
=> Update goth nightly stable branch regex

.github/workflows/goth-nightly.yml, .github/workflows/goth.yml, examples/blender/blender.ts, examples/yacat/yacat.ts, package.json, yajsapi/executor/index.ts, yajsapi/rest/activity.ts, yajsapi/rest/payment.ts, yajsapi/utils/asyncWith.ts, yajsapi/utils/log.ts
New features:
- #231 
- #239 
- #241 
- #230 
- #248 
- #229 
- #238
=> New features from master to b0.4

examples/blender/blender.js, examples/blender/blender.ts, examples/yacat/yacat.ts, tests/goth/pyproject.toml, tests/goth/test_agreement_termination/requestor.js, tests/goth/test_multiactivity_agreement/requestor.js, yajsapi/executor/index.ts
=> Default driver/network: erc20/rinkeby

examples/blender/blender.js, examples/blender/blender.ts, examples/yacat/yacat.ts
=> Add payment-driver and payment-network options

examples/hello-world/Dockerfile
as there is one in the [yapapi equivalent](https://github.com/golemfactory/yapapi/blob/master/examples/hello-world/Dockerfile) of this repo, i figured there should be one for this one too
=> add Dockerfile

yajsapi/utils/log.ts
This reverts commit 8055fbb4ecc5762e47563ae8e2f71e995b1aec12.
=> Revert "Fix Winston log level type (to b0.6) (#280)"

yajsapi/utils/log.ts
This reverts commit e6bf34c93f56373f3d387639994ef12c6ebab9cb.
=> Revert "Fix Winston log level type (#279)"

.github/workflows/goth-nightly.yml, tests/goth/pyproject.toml, tests/goth/test_run_blender.py, tests/goth/test_run_ssh.py, tests/goth/test_run_yacat.py
* make nightlies use only the master
* fix goth runs
=> update the configuration of the integration tests

tutorial.md
=> 355 taks api new features description markdown

examples/blender/blender.js, examples/hello-world/hello.js, examples/low-level-api/listOffers.ts, tests/goth/conftest.py, tests/goth/pyproject.toml, tests/goth/test_agreement_termination/test_agreement_termination.py, tests/goth/test_multiactivity_agreement/test_multiactivity_agreement.py, tests/goth/test_run_blender.py, tests/goth/test_run_yacat.py, yajsapi/executor/index.ts
=> update the name of the default subnet to `public`

yajsapi/executor/config.ts, yajsapi/executor/executor.ts
This PR adds repoUrl param to package config and makes the config in general to be used when generating the package
=> Fix package config

package.json, tests/unit/env_utils.test.ts, yajsapi/activity/config.ts, yajsapi/agreement/config.ts, yajsapi/executor/executor.ts, yajsapi/market/config.ts, yajsapi/network/config.ts, yajsapi/network/identity.ts, yajsapi/payment/accounts.ts, yajsapi/payment/config.ts, yajsapi/utils/env.ts, yajsapi/utils/index.ts
Should solve this: https://github.com/golemfactory/yagna-sdk-team/issues/265
=> Fixed process.env related bug (#265)

src/executor/config.ts
JST-80: Fixed the option to define the minimum number of cores for Demand
=> fix(demand): fixed minCpuCore option

src/executor/executor.ts
=> Feature/jst 516 - option to disable signals

examples/docs-examples/quickstarts/retrievable-task/task.mjs, tests/examples/examples.json
This PR adds the code from here https://docs.golem.network/docs/quickstarts/retrievable-task#creating-a-retrievable-task-2 which we want to replace with code fetched directly from Github.
=> test(examples): add missing doc example

.prettierignore, src/activity/activity.ts, src/activity/config.ts, src/executor/executor.ts, src/script/script.ts, src/task/batch.ts, tests/unit/activity.test.ts
=> fix: fixed issue with too long result polling interval leading to batch timeout

examples/blender/blender.ts, examples/docs-examples/examples/executing-tasks/on-activity-ready.mjs, src/executor/executor.ts, src/golem_network/golem_network.ts, src/task/service.ts, src/task/task.ts, src/task/work.spec.ts, src/task/work.ts, tests/e2e/blender.spec.ts, tests/e2e/gftp.spec.ts, tests/unit/golem_network.test.ts, tests/unit/tasks_service.test.ts
=> JST-101: deprecate beforeach, replace with `onActivityReady`

src/executor/config.ts, src/executor/executor.spec.ts, src/executor/executor.ts
Cherry-picking the feature to latest from beta
=> feat(executor): customize the behavior of startupTimeout with exitOnNoProposals flag

src/market/config.ts, src/market/demand.ts, src/market/factory.test.ts, src/market/factory.ts, src/market/service.ts
JST-622
Previously this option was taken from the counter proposal made by the provider.
=> feat: added support mid-agreement debit note interval configuration option

src/utils/yagna/gsb.ts, tests/docker/Provider.Dockerfile
Caused an error when uploading files via WebsocketStorageProvider (in browser)
=> Fixed missing header in gsb api

examples/external-request/manifest.json, examples/external-request/request.ts, src/agreement/factory.ts, src/events/events.ts, src/market/demand.ts, src/stats/providers.ts, src/stats/service.ts, tests/unit/stats.test.ts, tests/unit/stats_service.test.ts
The previous example did not run properly and required a provider with a whitelisted url to coingecko.com to work properly. I changed the example to use the url from ipfs.io, which is whitelisted by default.
Additionally, I fixed bugs with the ProviderInfo attribute in the ProposalRejected event and the stats service.
=> Outbound example fixes

examples/docs-examples/examples/transferring-data/transfer-data-in-browser.html, examples/docs-examples/examples/transferring-data/upload-json-in-browser.html, examples/docs-examples/quickstarts/web-quickstart/requestor.mjs, examples/docs-examples/tutorials/accessing-internet/outbound-ipfs.mjs, examples/docs-examples/tutorials/running-from-browser/index.html, examples/package-lock.json, examples/simple-usage/spawn.ts, src/executor/executor.ts, src/market/proposal.ts, src/payment/service.ts, src/task/work.ts, tests/mock/services/payment.ts, tests/unit/tasks_service.test.ts
BREAKING CHANGE: `PaymentService.acceptDebitNote` is no longer available, use `acceptPayments` instead.
=> Remove deprecated method

examples/experimental/reputation/basic.ts, src/experimental/reputation/index.ts, src/experimental/reputation/system.ts, src/experimental/reputation/types.ts
This feature will allow to choose the best available provider based on benchmarking scores.
=> feat: experimental reputation client agreement selector

examples/basic/hello-world.ts, examples/deployment/new-api.ts, examples/package-lock.json, examples/pool/hello-world.ts, package-lock.json, src/activity/activity-pool.ts, src/activity/activity.module.ts, src/activity/activity.ts, src/activity/work/error.ts, src/agreement/agreement-pool.ts, src/agreement/agreement.ts, src/agreement/factory.ts, src/agreement/service.ts, src/experimental/new-api/deployment.ts, src/golem-network.ts, src/market/config.ts, src/market/demand.ts, src/market/draft-offer-proposal-pool.test.ts, src/market/draft-offer-proposal-pool.ts, src/market/error.ts, src/market/market.module.test.ts, src/market/market.module.ts, src/market/proposal.ts, src/market/proposals_batch.ts, src/market/service.ts, tests/unit/agreement.test.ts, tests/unit/agreement_pool_service.test.ts, tests/unit/demand.test.ts, tests/unit/market_service.test.ts
During the test, the draft offer proposals and agreements were not correctly released in the example of pool/hello-world. @mgordel, let's have a pair programming session on Monday.
=> Feature/jst 871/activity module new

examples/basic/hello-world.ts, examples/deployment/new-api.ts, examples/pool/hello-world.ts, src/activity/activity-pool.ts, src/agreement/agreement-pool.ts, src/agreement/agreement.ts, src/agreement/factory.ts, src/agreement/service.ts, src/experimental/new-api/deployment.ts, src/market/demand.ts, src/market/draft-offer-proposal-pool.ts, src/market/market.module.test.ts, src/market/market.module.ts, src/market/service.ts, tests/e2e/activityPool.spec.ts, tests/examples/examples.json
Working with payments still a TODO, addressed in a separate ticket. Fixing pool implementation means: to drain and clear (destroy) all instances upon a single request. Improved error logging because the current implementation was hard to debug and troubleshoot.
=> fix(beta): stabilized examples so that they work, fixed pool implementation

examples/basic/hello-world.ts, examples/deployment/new-api.ts, examples/market/scan.ts, examples/pool/hello-world.ts, src/experimental/new-api/builder.test.ts, src/experimental/new-api/builder.ts, src/experimental/new-api/deployment.ts, src/golem-network.ts, src/market/api.ts, src/market/builder.ts, src/market/demand.ts, src/market/draft-offer-proposal-pool.ts, src/market/index.ts, src/market/market.module.test.ts, src/market/market.module.ts, src/payment/payment.module.ts, src/shared/yagna/adapters/index.ts, src/shared/yagna/adapters/market-api-adapter.test.ts, src/shared/yagna/adapters/market-api-adapter.ts, tests/e2e/activityPool.spec.ts
This PR cannot be merged at the moment, I'm waiting for https://github.com/golemfactory/golem-js/pull/909 to be error-free before rebasing it here and fixing merge conflicts
=> Market API adapter and deprecate Allocation.create and Package

src/payment/PayerDetails.ts, src/payment/payment.module.ts
https://github.com/microsoft/TypeScript/issues/29729 for context
=> Fix payment driver/token types (allow any string)

package-lock.json, package.json, src/shared/yagna/adapters/network-api-adapter.ts
=> chore: updated ya-ts-client to 1.1.2

examples/advanced/step-by-step.ts, src/activity/activity.module.ts, src/activity/activity.ts, src/activity/api.ts, src/activity/exe-script-executor.test.ts, src/activity/exe-script-executor.ts, src/activity/work/batch.spec.ts, src/activity/work/batch.ts, src/activity/work/process.ts, src/activity/work/work.ts, src/golem-network/golem-network.ts, src/lease-process/lease-process-pool.ts, src/market/agreement/agreement.ts, src/market/api.ts, src/market/market.module.test.ts, src/market/market.module.ts, src/market/proposal/offer-proposal.ts, src/payment/agreement_payment_process.spec.ts, src/payment/agreement_payment_process.ts, src/payment/payment.module.ts, src/shared/yagna/adapters/activity-api-adapter.ts, src/shared/yagna/adapters/market-api-adapter.ts, src/shared/yagna/repository/activity-repository.ts, tests/unit/activity.test.ts, tests/unit/agreement.test.ts, tests/unit/work.test.ts
- added script sent event
- added counter offer sent event
- renamed `offerProposalRejectedByFilter` to `offerProposalRejectedByProposalFilter`
- added refreshing before emitting any events that include an activity
- added `previousState` to activity, so now `activityStateChanged` only gets emitted when the state actually changes
- renamed `activityInitialized` to `workContextInitialized`
- replaced `.getProviderInfo()` in all entities to `get provider()`
- added refreshing before emitting `allocationReleased`
=> Address events feedback

examples/advanced/proposal-filter.ts, examples/advanced/proposal-predefined-filter.ts, examples/advanced/proposal-selector.ts, src/experimental/deployment/deployment.ts, src/experimental/reputation/system.ts, src/experimental/reputation/types.ts, src/golem-network/golem-network.ts, src/market/draft-offer-proposal-pool.test.ts, src/market/draft-offer-proposal-pool.ts, src/market/index.ts, src/market/market.module.ts, src/market/proposal/offer-proposal.ts
refactor: renamed proposalSelector to OfferProposalSelector
=> refactor: renamed proposalFilter to OfferProposalFilter

examples/advanced/override-module.ts, examples/basic/events.ts, src/activity/activity.module.ts, src/activity/api.ts, src/activity/exe-unit/exe-unit.ts, src/golem-network/golem-network.ts, src/market/api.ts, src/market/draft-offer-proposal-pool.ts, src/market/market.module.ts, src/network/api.ts, src/network/network.module.ts, src/payment/api.ts, src/payment/payment.module.ts, src/resource-rental/resource-rental-pool.ts, src/resource-rental/resource-rental.ts, tests/e2e/resourceRentalPool.spec.ts
=> refactor: unified event representation across different types of events

package-lock.json, src/network/tcp-proxy.test.ts, src/network/tcp-proxy.ts
=> fix(tcp-proxy): throw an error when users try to use proxy in browser

src/golem-network/golem-network.test.ts, src/golem-network/golem-network.ts
After consuliation with @SewerynKras we decided to not include these changes into master
=> Remove changes
