- yajsapi/index.ts
- yajsapi/storage/gftp.ts
- yajsapi/storage/index.ts
Resolves golemfactory/yagna-integration#288. as it solves last piece of the requirement list.
- Keep event emitter clear
> prevent stream reader to initialize mutliple times

- package.json
- yajsapi/rest/activity.ts
- yajsapi/utils/log.ts
No changes when `-d` is not specified.
When it's specified, all command output (stdout and stderr) is appended to the log file. If a given command fails on a provider, its output is additionally printed to the console.
> Command output logs & getExecBatchResults timeout fix

- yajsapi/executor/index.ts
- yajsapi/executor/strategy.ts
- yajsapi/props/com.ts
- yajsapi/rest/market.ts
• Add computation price caps
• Fix HTTP 400 on `.reject()`
• Update default Executor timeout to 15 min (yapapi PR #255)
• Bug fix (`stdout` -> `stderr`)
> Add computation price caps

- yajsapi/executor/ctx.ts
- yajsapi/executor/index.ts
- yajsapi/index.ts
- yajsapi/rest/activity.ts
- yajsapi/rest/index.ts
> Return batch results with optional blocking

- .github/workflows/goth-nightly.yml
Additional improvement to: https://github.com/golemfactory/yagna-sdk-team/issues/122
This adds a job which obtains the latest stable branch name and uses that name to generate a run matrix definition for the proper testing job.
Doing so removes the need for manually updating the workflow file whenever there's a new stable branch created in the repo.
> Use dynamic stable branch in goth nightly

- .github/workflows/goth-nightly.yml
This also removes the auto-embed added to the message by Discord by wrapping the workflow URL in `<>`.
> Add team mention to goth nightly failure messages

- .github/workflows/goth-nightly.yml
- tests/goth/pyproject.toml
- tests/goth/test_agreement_termination/test_agreement_termination.py
- tests/goth/test_multiactivity_agreement/test_multiactivity_agreement.py
- tests/goth/test_run_blender.py
- tests/goth/test_run_yacat.py
This is to prevent an issue with one of `goth`'s transitive dependencies, a similar issue is decribed here: https://github.com/aws/aws-sam-cli/issues/3661
This PR also includes some Actions workflow improvements:
- integration test reruns for some specific exceptions using `pytest-rerunfailures`
- fix Actions job responsible for getting the latest stable branch name
> Update goth to version 0.10+

- examples/blender/blender.ts
- examples/fibonacci/fibonacci.js
- examples/mid-level-api/hello.ts
- examples/ssh/ssh.ts
- examples/web/executor/hello.html
- examples/web/executor/image.html
- examples/web/mid_level/index.html
- examples/yacat/yacat.ts
- tests/cypress/ui/hello_world.cy.ts
- tests/cypress/ui/mid_level.cy.ts
- tests/integration/blender.spec.ts
- tests/integration/mid_level.spec.ts
- tests/integration/ssh.spec.ts
- tests/integration/tasks.spec.ts
- tests/integration/yacat.spec.ts
- tests/mock/entities/allocation.ts
- tests/mock/fixtures/accounts.ts
- tests/mock/fixtures/debit_notes.ts
- tests/mock/fixtures/invoices.ts
- tests/unit/payment_service.test.ts
- yajsapi/executor/config.ts
- yajsapi/payment/config.ts
- yajsapi/payment/service.ts
Default payment updated to goerli. Maybe worth to mention that there are two config files with redundant payment config.  [yajsapi/executor/config.ts ](https://github.com/golemfactory/yajsapi/blob/master/yajsapi/executor/config.ts#L11) and [yajsapi/payment/config.ts](https://github.com/golemfactory/yajsapi/blob/master/yajsapi/payment/config.ts#L13) Also probably some check will fail as there are units that assumes to be run on rinkeby.
> Change default payment network rinkeby->goerli

- package.json
It’s weird.. because we have an integration test for this example:
https://github.com/golemfactory/yajsapi/blob/d7422f1fe6ef19188a44bde1e1176bd139658b75/tests/integration/tasks.spec.ts#L194
But normally everything works because the tmp package is installed also by cypress so when we install with yarn or npm everything works. The problem occurs when we install with the --production flag, then the tmp package is missing. I added a fix. It should now work with the --production flag as well.
> Added missing tmp package (JST-77)

- .husky/pre-commit
- package.json
- src/task/batch.ts
- src/task/work.ts
- tests/e2e/strategies.spec.ts
- tests/e2e/tasks.spec.ts
- tests/tsconfig.json
- tests/unit/work.test.ts
Fix: JST-64 - When a command executed in a batch fails on the provider, instead of throwing, it returns a 'Error' Result which improves debugging.
In addition, the batch is not retried on a different provider where the broken command could still incur additional cost (repeating the failure).
> Fix: JST-64 - Result with error for batch instead of throw

- src/agreement/strategy.ts
After retests, there was still a bug for the default provider selection strategy with priority for those who already have agreement created. Now it should all work.
> Fixed agreement selection strategy

- package.json
- rollup.config.mjs
I think the earlier error where we released versions without some files was caused by our temporary workaround where we ended the process with exit code 0 in case of suspension. Now, in each case in which an error occurs, the process will return an exit code !== 0, so there should be no problem and CI will stop entire process. Additionally, I added a validator for the file size.
> JST-300: added bundle size validator

- .github/workflows/ci.yml
- package.json
- src/executor/executor.ts
- src/storage/gftp.ts
JST-429: Fixed gftp bug with incorrect initialization when there are no tasks in the executor.
Additionally, gftp has been refactored, getting rid of the old `@rauschma/stringio` dependency which has been replaced with native nodejs modules.
> JST-429: Gftp bugfix and refactor

- src/executor/executor.spec.ts
- src/executor/executor.ts
> fix: task executor end() can be called multiple times

- examples/docs-examples/examples/composing-tasks/batch-endstream-chunks.mjs
- examples/docs-examples/examples/working-with-results/multi-command-endstream.mjs
- src/executor/executor.ts
- src/golem_network/golem_network.ts
- src/index.ts
- src/task/queue.ts
- src/task/service.ts
- src/task/task.ts
- src/task/work.ts
- tests/unit/tasks_service.test.ts
- tests/unit/work.test.ts
BREAKING CHANGE: worker type no longer takes two parameters
> JST-598: simplify worker type

- .docs/typedoc-frontmatter-theme.cjs
Right now on the beta branch, all overview.md files generated using `npm run docs:md` will be empty. This PR fixes it.
> Fix overview.md not being generated properly for docs.

- .github/workflows/cypress-nightly.yml
- .github/workflows/examples-nightly.yml
- .github/workflows/goth-nightly.yml
- .github/workflows/release.yml
The previous workflows only used default values for manual triggers, but nightly automated tests didn't use them thus the builds failed. This PR uses either values from the manual triggered workflow or else it defaults to new hardcoded values.
> Fix scheduled nightly tasks not picking up default values from workflow

- src/executor/config.ts
- src/executor/executor.spec.ts
- src/task/task.ts
- tests/e2e/tasks.spec.ts
- tests/unit/tasks_service.test.ts
The bug with `maxTaskRetries: 0`  does not exist, it was fixed somewhere earlier... I only added unit tests and e2e tests that verify this. Additionally, I added validation of the maxTaskRetries parameter. Now throws an error for a value less than zero.
> maxTaskRetries validation

- .github/workflows/release.yml
It's unfortunately not possible to use ENV values to name a run, so automated triggers of the release pipeline might not have the version defined in the title, but the workflow should still work.
> Add requestor / provider versions to workflow name to make it easier to see #681

- rollup.config.mjs
The spawn method did not work in the browser because we ignored the eventsource library in the build
> Fix incorrect rollup configuration for eventsource

- src/agreement/agreement.ts
- src/agreement/factory.ts
- src/events/events.ts
- src/market/demand.ts
- src/market/factory.ts
- src/market/proposal.test.ts
- src/market/proposal.ts
- src/payment/agreement_payment_process.test.ts
- src/payment/debit_note.ts
- src/payment/invoice.test.ts
- src/payment/invoice.ts
- src/payment/payments.ts
- src/payment/service.ts
- src/stats/agreements.ts
- src/stats/invoices.ts
- src/stats/payments.ts
- src/stats/service.ts
- src/task/service.ts
- tests/mock/entities/agreement.ts
- tests/mock/services/agrrement_pool.ts
- tests/unit/agreement_pool_service.test.ts
- tests/unit/demand.test.ts
- tests/unit/stats.test.ts
- tests/unit/stats_service.test.ts
Evets that contained the `providerId` and/or `providerName` fields now return an object of the `ProviderInfo` type, which consists of `id`, `name` and `walletAddress`
By the way, I corrected the `amount` field, which was a string
> Wallet address field in payment events

- src/agreement/factory.ts
- src/market/demand.ts
- src/market/proposal.test.ts
- src/market/proposal.ts
- src/market/proposals_batch.test.ts
- src/market/proposals_batch.ts
- src/market/service.ts
- tests/unit/market_service.test.ts
This PR contains a new class `ProposalsBatch` which is used to group Initial Proposals. Each Initial Proposal received in `MarketService` is added to Batch, then at an interval the proposals are fetched grouped according to the provider key distinguished by provider ID and hardware configuration in order to avoid duplication of offers.
> Proposals batching

- .github/actions/cleanup-tests/action.yml
- .github/workflows/release.yml
Fixed log generation from yagna for requestr and providers during e2e, cypress and examples tests. Now there are separate packages for each type of tests
> Ci pipeline test logs fix

- src/network/network.ts
- src/network/service.ts
- src/task/service.ts
- tests/mock/rest/network.ts
- tests/mock/services/network.ts
- tests/unit/network.test.ts
- tests/unit/network_service.test.ts
- tests/unit/tasks_service.test.ts
Fixed a bug related to adding a node to the network. There was no checking whether the node existed. Additionally, added the ability to remove a node from the network and handle it in TaskService.
> fix(network): fixed adding an existing node to the network

- src/activity/activity.ts
- src/events/events.ts
- src/executor/config.ts
- src/executor/executor.ts
- src/task/service.ts
- src/task/task.ts
- tests/e2e/strategies.spec.ts
- tests/e2e/tasks.spec.ts
- tests/unit/tasks_service.test.ts
Now the task timeout is measured for each attempt separately.
Additionally, I refactored the task service by separating individual blocks into startTask, retryTask and stopTask. They are triggered by a change in the task state.
I added another state for the task - `queued`. Now, when we start the task, the task changes its state from new -> queued and when agreement and activity are created, the task starts (state pending) and from that moment the timeout is counted. It seems that this approach is better, because now the duration of the task is counted from the moment of running the first activity command (deploy) and this does not include negotiations with the market.
> fix(task): fixed retrying and timeout measurement for task

- src/agreement/config.ts
- src/agreement/service.ts
- src/executor/config.ts
- tests/mock/rest/market.ts
- tests/unit/agreement.test.ts
- tests/unit/agreement_pool_service.test.ts
Added a mechanism for checking whether the pool is full when releasing an agreement.
By default, the agreementMaxPoolSize parameter is set by TaskExecutor with a value equal to maxParallelTasks
> fix(agreement_pool): added agreement pool size limit

- src/payment/allocation.ts
- src/payment/config.ts
AllocationOptions property `expires` got renamed to `expirationSec` and the value should be `seconds` instead of `milliseconds`
> fix(payment): renamed expires parameter to expirationSec for the Allocation

- src/task/process.ts
- tests/e2e/tasks.spec.ts
In the case of a timeout at `waitForExit` on spawned process (ctx.spawn), the activity will be correctly terminated, and it will be possible to perform next tasks on other providers.
> fix(spawn): terminating spawned activity in case of timeout

- src/agreement/agreement.ts
- src/executor/index.ts
- src/golem_network/golem_network.ts
- src/index.ts
- src/market/config.ts
- src/market/demand.ts
- src/network/network.ts
- src/payment/config.ts
- src/payment/index.ts
- src/payment/service.ts
- src/utils/index.ts
I'm not sure if it's OK to enable everything in `index.ts` using `export * ...`. But anyone can get to these elements using `import from golem-js/dist/...` so I guess it's not a big difference..?
> fix: enabling imports needed for external libraries

- src/events/events.ts
- src/payment/agreement_payment_process.spec.ts
- src/payment/agreement_payment_process.ts
- src/payment/debit_note.spec.ts
- src/payment/debit_note.ts
- src/payment/invoice.spec.ts
- src/payment/invoice.ts
- src/payment/payments.ts
- src/payment/strategy.ts
- src/stats/invoices.ts
- src/stats/payments.ts
- src/stats/service.ts
- tests/unit/stats.test.ts
- tests/unit/stats_service.test.ts
Added `amountPrecise` in Invoice and `totalAmountDuePrecise` in DebitNote. The old fields `amount` and `totalAmountDue` are marked as **deprecated**.
The number type caused problems for big numbers. The new `amountPrecise` and `totalAmountDuePrecise` fields are of the string type, and it is recommended to use them instead of the ones mentioned above. Payment events also have new fields for storing `amountPrecise` values.
> fix(payments): fixed payment acceptance for big number amount

- src/events/events.ts
- src/payment/agreement_payment_process.spec.ts
- src/payment/debit_note.spec.ts
- src/payment/debit_note.ts
- src/payment/invoice.spec.ts
- src/payment/invoice.ts
- src/payment/strategy.test.ts
- src/payment/strategy.ts
fix(payments): restoring string types for the amount and totalAmountDue fields
BREAKING CHANGE: Removed the `amountPrecise` field in `Invoice` and
`totalAmountDuePrecise` in `DebitNote`. Now the old `amount` and
`totalAmountDue` fields are of the string type, so the above will be
unnecessary.
> Master -> beta sync

- src/lease-process/lease-process.ts
- src/market/agreement/agreement.ts
- src/payment/agreement_payment_process.ts
- src/payment/payment.module.ts
- src/shared/yagna/adapters/payment-api-adapter.ts
If the agreement is terminated on the provider's side, we should not send a request to yagna for termination.
In addition, in the case of debitNote/Invoice rejection e.g. due to filters, we should not send a request to the endpoint reject - Yagna has not implemented this and always responds 501:NotImplented
> fix(lease-process): fixed finalizing already terminated agreements

- src/activity/activity.module.ts
- src/activity/config.ts
- src/activity/exe-script-executor.test.ts
- src/activity/exe-script-executor.ts
- src/activity/work/work.ts
- src/golem-network/golem-network.ts
- src/lease-process/lease-process-pool.test.ts
- src/lease-process/lease-process-pool.ts
- src/lease-process/lease-process.ts
- src/market/draft-offer-proposal-pool.test.ts
- src/market/draft-offer-proposal-pool.ts
- src/market/market.module.test.ts
- src/market/market.module.ts
- tests/e2e/leaseProcessPool.spec.ts
- tests/unit/work.test.ts
This PR includes:
- removed the default timeout in draft-proposal-pool, instead added the `signalOrTimeout` parameter in the acquire method
- added `signalOrTimeout` parameter to `oneOf` in golem-network
- added `signalOrTimeout` parameter to `acquire` in lease-proposal-pool
- changed `timeout` to `signalOrTimeout` parameter in `CommandOptions` in work-context
- added `signalOrTimeout` parameter to `signAgreementFromPool` in market-module
- removed `activityExecutionTimeout`  and `timeout` param in `execute` in exe-script-executor, instead added `signalOrTimeout` param in constructor (to cancel all executions) and in `execute` method (to cancel single execution)
> feat: added ability to cancel lease processes

- src/resource-rental/resource-rental.test.ts
- src/resource-rental/resource-rental.ts
`ResourceRental.destroyExeUnit` was already added
> Creation of exe-unit during resource-rental startup

- src/market/proposal/offer-proposal.test.ts
- src/market/proposal/offer-proposal.ts
Adjust the code in the OfferProposal.getEstimate to handle optional parameter of rentHours (default 1) and will use this to provide the estimation
> fix(market): proposals are now estimated with 1h duration by default

- examples/experimental/express/server.ts
- package.json
1. Vite supports `browser` condition is conditional exports: https://vitejs.dev/config/shared-options#resolve-conditions
2. `"browser" : null` disallows importing from `/experimental` in the browser (we don't create a build for it anyway, so this is not a new change, more of a formality)
3. (unrelated bugfix but I might as well add it here) the file `experimental.d.ts` no longer exists because we moved the file structure and didn't update this export, so I updated it to use the correct `experimental/index.d.ts`
> fix: add missing conditional export for browsers

- src/activity/exe-script-executor.ts
- src/activity/exe-unit/batch.ts
- src/activity/exe-unit/process.ts
- src/shared/yagna/yagnaApi.ts
This PR introduces fixes to logs that were needed to troubleshoot streaming batch results to the user.
I've also added the feature helping to wait for the `RemoteProcess` to reach "finished" state when the underlying exe-batch result is finished.
Allows such use-cases:
```ts
// Wait for the process to exit
await waitFor(() => proc.isFinished(), {
abortSignal: abort.signal,
});
```
> Grisha/developer experience improvements 24.07.11

- src/resource-rental/resource-rental.ts
This unhandled promise caused unhandled rejection if the signal was aborted before `getExeUnit()` was executed. I added `null` for the catch because another catch will handle logging and triggering the error event. However, error propagation should only take place if this method is called via `getExeUnit()`. Automatic creation of exe-unit from the constructor should ignore the error.
> fix(resource-rental): fixed error handling when creating an exe-unit

- examples/rental-model/basic/many-of.ts
- package-lock.json
- src/experimental/job/job.ts
- src/market/draft-offer-proposal-pool.test.ts
- src/market/draft-offer-proposal-pool.ts
- src/market/market.module.test.ts
- src/market/market.module.ts
- src/resource-rental/resource-rental-pool.test.ts
- src/resource-rental/resource-rental-pool.ts
- src/shared/utils/acquireQueue.ts
- tests/e2e/resourceRentalPool.spec.ts
The problems:
1. `DraftOfferProposalPool` uses a lock on `acquire` and `destroy`, so if someone is waiting for an offer, other offers cannot be destroyed. In the original bug after signing the first agreement we [remove the proposal from the pool after signing it](https://github.com/golemfactory/golem-js/blob/beta/src/market/market.module.ts#L560) which causes the deadlock.
2. Even with the above fixed, if we start trying to sign a new rental, there is no mechanism to stop waiting for an offer once another rental becomes available. If we run 3 tasks with only one provider, the first one gets done and the other 2 get stuck forever trying to `acquire` an offer proposal.
The solution:
1. Use the same acquire queue mechanism in `DraftOfferProposalPool` that we use in `ResourceRentalPool`. To …
> JST-1022: Create activities independently

- src/golem-network/golem-network.ts
In cases when the requestor does not have `gftp` installed (you can move the file to a different location to test this), `glm.disconnect()` was executed quickly and the script was not closing at all. Using `wtfnode` showed that after `glm.connect()` fails due to the missing `gftp`, some connections to yagna were open:
```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
- fd 1 (tty) (stdio)
- fd 2 (tty) (stdio)
- Sockets:
- 127.0.0.1:57112 -> 127.0.0.1:7465
- 127.0.0.1:57142 -> 127.0.0.1:7465
- 127.0.0.1:43576 -> 127.0.0.1:7465
- Timers:
- (10000 ~ 10 s) (anonymous) @ /home/ggodlewski/proj/golem/golem-js/tmp/broken-gftp.ts:2
```
This PR removes the redundant `isConnected` check during the `disconnect` method execution, allowing the code to actually close the yagna …
> fix: fixed the issue blocking GolemNetwork.disconnecte because of missing gftp

- examples/core-api/scan.ts
- src/market/demand/directors/workload-demand-director-config.ts
- src/market/demand/directors/workload-demand-director.test.ts
- src/market/demand/directors/workload-demand-director.ts
- src/market/demand/options.ts
- src/market/proposal/offer-proposal.ts
- src/market/scan/scan-director.ts
- src/market/scan/scanned-offer.ts
- src/market/scan/types.ts
The previous `engine` parameter has been marked as deprecated and will be replaced by `runtime.name` in the next versions
> feat(demand): added the ability to define runtime version as demand options

- src/market/proposal/offer-proposal.ts
- src/market/scan/scanned-offer.test.ts
- src/market/scan/scanned-offer.ts
This PR adds the feature of estimating the scanned offer cost by the SDK, so that users (the CLI) won't have to do it on its own
> feat(market): added getEstimatedCost to ScannedOffer

- src/experimental/reputation/system.ts
- src/market/helpers.ts
The dev-test domains will be removed at the end of the month, and we've moved the reputation domain to the root URL in preparation. Please merge this to ensure your code works with the new URL moving forward.
> fix: update reputation url

- src/activity/exe-unit/exe-unit.ts
- src/activity/script/command.ts
- src/golem-network/golem-network.ts
- src/network/node.ts
- src/resource-rental/resource-rental.ts
The deployment-time volume definition parameter is introduced in exe-unit 0.5.2 and yagna 0.17. This PR adds the API access to that feature. It's marked as experimental because of the yagna 0.17 development status (RC right now).
```ts
import {GolemNetwork} from "../src";
(async () => {
const glm = new GolemNetwork({
payment:{
network: "holesky"
}
});
try {
console.log("Connecting to Golem Network")
await glm.connect();
console.log("Acquiring resources from the market")
const rental = await glm.oneOf({
order: {
demand: {
workload: {
imageTag: "golem/node:latest",
minStorageGib: 1,
runtime: {
version: "0.5.2"
}
}
},
market: {
rentHours: 15/60,
pricing: {
avgGlmPerHour: 1,
model: "burn-rate"
},
}
},
volumes: {
data: {
path: "/custom-data",
sizeGib: 1
},
files: {
path: "/custom-files", …
```
> feat: added experimental volume support for golem-js

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package-lock.json
- rollup.config.mjs
This PR makes the SDK buildable `npm run build` with latest LTS Node.js which is 22
> build: changed supported node versions, added node 22

- src/activity/activity.module.ts
- src/activity/exe-unit/exe-unit.ts
- src/resource-rental/resource-rental.ts
- tests/e2e/resourceRentalPool.spec.ts
Providing a timeout to `getExeUnit` would incorrectly shut down the internal executor after the specified time even if the activity deployed correctly, which would in turn shut down the whole exe-unit. This is now fixed
> fix(exe-unit): fixed setup timeout shutting down the internal executor regardless of success
